version: '2.1'

services:
    proxy:
        container_name: base-proxy
        hostname: base-proxy
        image: spydemon/nginx-proxy:0.1
        networks:
            - base
        ports:
            - "80:80"
            - "443:443"
        userns_mode: 'host'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./config/ssl:/etc/nginx/certs
    mail:
        container_name: base-mailhog
        environment:
            VIRTUAL_HOST: mail.local
            VIRTUAL_PORT: 8025
        expose:
            - "1025"
            - "8025"
        hostname: base-proxy
        image: mailhog/mailhog:latest
        networks:
            - base
    se_grid:
        container_name: base-se_grid
        extra_hosts:
             - "magento24.local:172.17.0.1"
             - "xemenao.local:172.17.0.1"
             - "tiroucubo.local:172.17.0.1"
        hostname: base-se_grid
        image: spydemon/se-grid-standalone:0.1
        networks:
            - base
        ports:
            - "6901:5900"
        # Sharing /dev/shm avoid browsers to randomly crash because shared memory available is insufficient.
        volumes:
            - /dev/shm:/dev/shm

networks:
    base:
        external: true
