version: '2.1'

services:
    proxy:
        container_name: base-proxy
        image: spydemon/nginx-proxy:0.1
        networks:
            - base
        ports:
            - "80:80"
            - "443:443"
        userns_mode: 'host'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./config/ssl:/etc/nginx/certs
    mail:
        container_name: base-mailhog
        environment:
            VIRTUAL_HOST: mail.local
            VIRTUAL_PORT: 8025
        expose:
            - "1025"
            - "8025"
        image: mailhog/mailhog:latest
        networks:
            - base

networks:
    base:
        external: true
